### ISSUE TITLE
Migrations in Tenant Databases

### ISSUE THREAD

**Issue by DeivCodeCamp** [orchestral/tenanti#52]
maybe i'm short in knowledge but i'm having problems with the migrations of the tables in the tenant databases.
my primary database is main and the tenant databases are names of companies, i get the value from a custom field in the table users (company).

I have the driver migrations in this path.
```
'drivers' => [
        'user' => [
            'model'  => App\User::class,
            'path'   => database_path('tenanti/user'),
            'shared' => false,
        ],
    ],
```
And i want to migrate with this sentence `php artisan tenanti:migrate user` but i get this error.

```
[ErrorException]
Creating default object from empty value

```
do you know what is happening? do you need more information?

I thank you in advance.
David

**Comment by crynobone** [comment]
What's the error stack trace for this?

**Comment by DeivCodeCamp** [comment]
This is the error.
```
[2017-08-18 13:38:25] local.ERROR: ErrorException: Creating default object from empty value in C:\Apache24\htdocs\FacStock\database\tenanti\user\2017_08_16_170805_user_tenant_empresas_table.php:18
Stack trace:
#0 C:\Apache24\htdocs\FacStock\database\tenanti\user\2017_08_16_170805_user_tenant_empresas_table.php(18): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Creating defaul...', 'C:\\Apache24\\htd...', 18, Array)
#1 C:\Apache24\htdocs\FacStock\vendor\orchestra\tenanti\src\Migrator\Migrator.php(109): UserTenantEmpresasTable->up(1, Object(App\User))
#2 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(146): Orchestra\Tenanti\Migrator\Migrator->runUp('2017_08_16_1708...', 1, false)
#3 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(95): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#4 C:\Apache24\htdocs\FacStock\vendor\orchestra\tenanti\src\Migrator\Factory.php(173): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#5 C:\Apache24\htdocs\FacStock\vendor\orchestra\tenanti\src\Migrator\Factory.php(79): Orchestra\Tenanti\Migrator\Factory->runUp(Object(App\User), 'tenants_1', false)
#6 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Database\Concerns\BuildsQueries.php(39): Orchestra\Tenanti\Migrator\Factory->Orchestra\Tenanti\Migrator\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#7 C:\Apache24\htdocs\FacStock\vendor\orchestra\tenanti\src\Migrator\Operation.php(83): Illuminate\Database\Eloquent\Builder->chunk(100, Object(Closure))
#8 C:\Apache24\htdocs\FacStock\vendor\orchestra\tenanti\src\Migrator\Factory.php(81): Orchestra\Tenanti\Migrator\Factory->executeByChunk(Object(Closure))
#9 C:\Apache24\htdocs\FacStock\vendor\orchestra\tenanti\src\Console\MigrateCommand.php(47): Orchestra\Tenanti\Migrator\Factory->run(NULL, NULL, false)
#10 [internal function]: Orchestra\Tenanti\Console\MigrateCommand->handle()
#11 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#12 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Container\Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Illuminate\Container\Container->call(Array)
#16 C:\Apache24\htdocs\FacStock\vendor\symfony\console\Command\Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Console\Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 C:\Apache24\htdocs\FacStock\vendor\symfony\console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\Apache24\htdocs\FacStock\vendor\symfony\console\Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Orchestra\Tenanti\Console\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\Apache24\htdocs\FacStock\vendor\symfony\console\Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\Apache24\htdocs\FacStock\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\Apache24\htdocs\FacStock\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}
```

Thanks for  your time!

**Comment by arturcesarmelo** [comment]
I don't know if i can help you at this time. But i have a problem with artisans command when i tried to set up a config file using functions to fill the array keys ( as you dit in 'path'   => database_path('tenanti/user')". Try to write the path manually and see what happen.

**Comment by h2akim** [comment]
Not sure this is still issue for @DeivCodeCamp or not.

Seems like there's no id column in your main table?

**Comment by Punksolid** [comment]
@DeivCodeCamp same problem here, how did you solve it? When using shared database true, I could use ```php artisan tenanti:install user``` but when doing it with shared database in false, looks for database user_1 which does not exist yet. I thought it would create it.

So, is there a way to do it with the actual package? or do I need it to do it myself and then continue to use the package. I don't see it clearly on the documentation and didn't find that feature on the codebase. 

Thanks
